export enum Navigator {
  AuthStack = 'AuthStack',
  FloorStack = 'FloorStack',
  MainTab = 'MainTab',
  ProfileStack = 'ProfileStack',
  HomeStack = 'HomeStack',
  ExplorationStack = 'ExplorationStack',
  NotificationStack = 'NotificationStack',
  CreateFloorStack = 'CreateFloorStack',
}

export enum Screen {
  LoginScreen = 'LoginScreen',
  TermsFormScreen = 'TermsFormScreen',
  PersonalDataFormScreen = 'PersonalDataFormScreen',
  UserProfileFormScreen = 'UserProfileFormScreen',
  WelcomeScreen = 'WelcomeScreen',
  HomeScreen = 'HomeScreen',
  SearchScreen = 'SearchScreen',
  GroupFeedScreen = 'GroupFeedScreen',
  NotificationScreen = 'NotificationScreen',
  ProfileScreen = 'ProfileScreen',
  AddHashtagScreen = 'AddHashtagScreen',
  FloorInfoFormScreen = 'FloorInfoFormScreen',
  ImageDetailScreen = 'ImageDetailScreen',
  FloorViewerScreen = 'FloorViewerScreen',
  EditFloorScreen = 'EditFloorScreen',
  GuestBookScreen = 'GuestBookScreen',
  MyProfileScreen = 'MyProfileScreen',
  EditProfileScreen = 'EditProfileScreen',
  SettingScreen = 'SettingScreen',
  FollowListScreen = 'FollowListScreen',
  ExplorationScreen = 'ExplorationScreen',
  HashtagFloorScreen = 'HashtagFloorScreen',
  OnboardingScreen = 'OnboardingScreen',
}
